name: Terraform Plan Check

on:
  push:
    branches:
      - master
      - main
      - feature/*
  pull_request:  # To ensure that pull requests are also checked

permissions:
  contents: read
  issues: write

jobs:
  terraform_plan_check:
    name: Terraform Plan Check
    runs-on: ubuntu-latest
    environment: DEV   # Use the environment where the secrets are configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use the secret from the DEV environment
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use the secret from the DEV environment
          aws-region: eu-west-1

      - name: Make setup_infrastructure.sh executable
        run: chmod +x ./scripts/setup_infrastructure.sh

      - name: Run setup_infrastructure.sh
        run: ./scripts/setup_infrastructure.sh ${{ github.actor }}

      # Initialize Terraform with Local Backend for Backend Infrastructure
      - name: Initialize Terraform with Local Backend for Backend
        working-directory: ./iac/backend
        run: |
          echo "Using local backend for Terraform."
          cat > backend.tf <<EOF
          terraform {
            backend "local" {
              path = "./terraform.tfstate"
            }
          }
          EOF
          terraform init

      - name: Terraform Plan for Backend
        working-directory: ./iac/backend
        run: terraform plan

      # Initialize Terraform with Local Backend for CICD Infrastructure
      - name: Initialize Terraform with Local Backend for CICD
        working-directory: ./iac/management
        run: |
          echo "Using local backend for Terraform."
          cat > backend.tf <<EOF
          terraform {
            backend "local" {
              path = "./terraform.tfstate"
            }
          }
          EOF
          terraform init

      - name: Terraform Plan for Management
        working-directory: ./iac/management
        run: terraform plan
